### ISSUE TITLE
what's the difference between your dataset and the offical

### ISSUE THREAD

**Issue by flygyyy** [jiecaoyu/pytorch-nin-cifar10#2]
can you explain the details, do you use Normalize?

**Comment by jiecaoyu** [comment]
@flygyyy Hi, my dataset is generated from [here](https://gist.github.com/mavenlin/e56253735ef32c3c296d). I changed it into lmdb to read it from PyTorch.

The dataset is preprocessed as described in [Maxout Network](https://arxiv.org/pdf/1302.4389.pdf):"We preprocess the data using global contrast normalization and ZCA whitening."

**Comment by flygyyy** [comment]
Thanks for your reply, best regards.
